server:
  port: 51001
server-ip: 127.0.0.1
spring:
  profiles:
    active: dev
  application:
    name: app-business-gateway-demo
  boot:
    admin:
      client:
        url: http://47.92.122.231:50000/
        username: admin
        password: 123456
        instance:
          prefer-ip: true
          service-url: http://${server-ip}:${server.port}/
          name: app-business
#actuator监控
management:
  client:
    # 设置监控服务端口
    port: 50554
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
logging:
  level:
    root: info
vma:
  resource:
    upload:
      qiniu:
        access-key: -V2tA9xmyVKb0GRkH_MrJJXbNwwn0PQDi29lNFip
        secret-key: TRB4swL5N_kBCib_coKU3keHxN5ksAQMv5vQuiWD
        bucket: keji
        domain-url: https://keji-res.h5h5h5.cn
