spring:
  datasource:
    url: jdbc:mysql://114.118.97.41:3307/scrm_business?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: chenz
    password: 1hM9zxOsrpb#
  redis:
    host: 47.98.182.15
    port: 8888
    password: hKTM0xe7E3
    database: 0

logging:
  file: nohup.out