spring:
  application:
    name: app-business-client
  profiles:
    active: dev
logging:
  level:
    com.vma.app.cloud.ApiCloud: DEBUG
feign:
  # TODO
  # feign.server-name配置为app-server的spring.application.name
  server-name: app-business