spring:
  application:
    name: app-cloud-server-demo
  profiles:
    active: dev
logging:
  level:
    root: info
    com.vma.app.cloud.ApiCloud: DEBUG
custom:
  cloud:
    api: https://ca01.xmtryz.cn/api/
vma:
  cloud:
    server:
      csrf-ignoring-ant-matchers: /**