spring:
  application:
    name: app-business-gateway-demo
  profiles:
    active: dev
vma:
  resource:
    upload:
      # 文件上传临时目录
      templateUpload:
      qiniu:
        access-key: -V2tA9xmyVKb0GRkH_MrJJXbNwwn0PQDi29lNFip
        secret-key: TRB4swL5N_kBCib_coKU3keHxN5ksAQMv5vQuiWD
        bucket: keji
        domain-url: https://keji-res.h5h5h5.cn
