spring:
  datasource:
    url: jdbc:mysql://39.100.197.27:4000/vmachat_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    userName: huangjb
    password: M{;qve<.rtp1!m
  redis:
    host: 39.100.13.36
    port: 8888
    password: v4YME3DcgTlKj
    database: 0