server:
  ip: 127.0.0.1
  port: 51001
spring:
  boot:
    admin:
      client:
        url: http://47.92.122.231:50000/
        username: admin
        password: 123456
        instance:
          prefer-ip: true
          service-url: http://${server.ip}:${server.port}/
          name: app-business
#actuator监控
management:
  client:
    # 设置监控服务端口
    port: 50554
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.apache.tomcat: info
    org.apache.coyote: info
    org.apache.coyote.http11.Http11Processor: info
    org.apache.http: info
    sun.net.www.protocol: info
    org.apache.catalina: info
    de.codecentric.boot: info