server:
  ip: 127.0.0.1
  port: 51001
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.apache.tomcat: info
    org.apache.coyote: info
    org.apache.coyote.http11.Http11Processor: info
    org.apache.http: info
    sun.net.www.protocol: info
    org.apache.catalina: info
    de.codecentric.boot: info